### PR TITLE
[WIP] Add Binary instances for Typeable TypeReps

### PR DESCRIPTION
**Pull request by bgamari**
This adds instances for `Typeable` types, both pre- and post-GHC 8.2's type-indexed `Typeable` support.

### CODE REVIEW

**Comment by kolmodin** [comment]
Thanks! It's nearly 200 lines of handwritten serialisation, can I trouble you for some unit tests as well?

**Comment by kolmodin** [comment]
Ping @bgamari.

**Comment by bgamari** [comment]
Yes, it's on my list.

**Comment by bgamari** [comment]
I've added a set of tests. I also removed the instances for GHC < 8.0 since I realized that this would result in overlapping instances as the same instances are already provided by the `ghci` package.

Regardless, things pass with GHC 8.2.

**Comment by kolmodin** [comment]
@bgamari, I wanted to run the tests on my machine, or at least compile `binary`, but I have so far not succeeded.

I assume this cabal version is too old, since it fails to install the dependencies for test.
```
$ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
```

```
$ cabal install --only-dependencies --enable-tests --with-ghc $HOME/usr-ghc-HEAD/bin/ghc
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: base-4.10.0.0/installed-4.1... (dependency of binary-0.8.4.1)
trying: tf-random-0.5 (dependency of QuickCheck-2.9.2)
next goal: primitive (dependency of tf-random-0.5)
rejecting: primitive-0.6.2.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4.5 && <4.10)
rejecting: primitive-0.6.1.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4.3 && <4.10)
rejecting: primitive-0.5.4.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4.3 && <4.9)
rejecting: primitive-0.5.3.0, primitive-0.5.2.1 (conflict:
base==4.10.0.0/installed-4.1..., primitive => base>=4.3 && <4.8)
rejecting: primitive-0.5.1.0 (conflict: base==4.10.0.0/installed-4.1...,
primitive => base>=4 && <4.8)
rejecting: primitive-0.5.0.1, primitive-0.5, primitive-0.4.1,
primitive-0.4.0.1, primitive-0.4, primitive-0.3.1, primitive-0.3 (conflict:
base==4.10.0.0/installed-4.1..., primitive => base>=4 && <4.7)
rejecting: primitive-0.2.1, primitive-0.2, primitive-0.1 (conflict: tf-random
=> primitive>=0.3)
rejecting: primitive-0.6 (conflict: base==4.10.0.0/installed-4.1..., primitive
=> base>=4.3 && <4.9)
Dependency tree exhaustively searched.
```

So, proceeding to just compiling `binary`.
```
$ cabal build --with-ghc=$HOME/usr-ghc-HEAD/bin/ghc
Building binary-0.8.4.1...
Preprocessing library binary-0.8.4.1...
[1 of 9] Compiling Data.Binary.Builder ( src/Data/Binary/Builder.hs, dist/build/Data/Binary/Builder.o )
[2 of 9] Compiling Data.Binary.FloatCast ( src/Data/Binary/FloatCast.hs, dist/build/Data/Binary/FloatCast.o )
[3 of 9] Compiling Data.Binary.Internal ( src/Data/Binary/Internal.hs, dist/build/Data/Binary/Internal.o )
[4 of 9] Compiling Data.Binary.Get.Internal ( src/Data/Binary/Get/Internal.hs, dist/build/Data/Binary/Get/Internal.o )
[5 of 9] Compiling Data.Binary.Get  ( src/Data/Binary/Get.hs, dist/build/Data/Binary/Get.o )
[6 of 9] Compiling Data.Binary.Put  ( src/Data/Binary/Put.hs, dist/build/Data/Binary/Put.o )
[7 of 9] Compiling Data.Binary.Class ( src/Data/Binary/Class.hs, dist/build/Data/Binary/Class.o )

src/Data/Binary/Class.hs:77:1: error:
    Could not find module ‘Type.Reflection’
    Use -v to see a list of the files searched for.
   |
77 | import Type.Reflection
   | ^^^^^^^^^^^^^^^^^^^^^^

src/Data/Binary/Class.hs:78:1: error:
    Could not find module ‘Type.Reflection.Unsafe’
    Use -v to see a list of the files searched for.
   |
78 | import Type.Reflection.Unsafe
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I assume my version of GHC is too old as well.
```
$ ~/usr-ghc-HEAD/bin/ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.1.20170215
```

Currently installing cabal and GHC from their `master` branches, will try again.

**Comment by bgamari** [comment]
No need to try again until I merge the GHC commit moving the instances, which I could not do until this PR was merged. I'll do this shortly.

**Comment by kolmodin** [comment]
I built GHC 8.1.20170225, `8f15ab98a7fe7484089b48c94328fa2980978890`, all the tests passed.

**Comment by kolmodin** [comment]
Thanks @bgamari! I'll release this as 0.9.0.0.

**Comment by kolmodin** [comment]
This patch resulted in a lot of compiler warnings for all GHC versions prior to GHC 8.2. I'd like to fix those, then release `0.9.0.0`.

**Comment by kolmodin** [comment]
@bgamari ^^

**Comment by bgamari** [comment]
See #135.

**Comment by kolmodin** [comment]
About half of the code in this patch are not covered in the QC tests. But, won't harass you any more, I'll release `0.9.0.0`... :)

**Comment by bgamari** [comment]
You caught me red-handed; I neglected to run `hpc` on this one.

**Pull request merged**
