### PR TITLE
Don't use tyConString

### PR DESCRIPTION
**Pull request by treeowl**
`tyConString` has been deprecated since GHC 7.4. I'd like to move toward actually removing it. That can't happen until `binary` stops using it.

### CODE REVIEW

**Comment by treeowl** [comment]
Actually, I guess it's not *that* urgent, since the library itself will build without `tyConString`, but the example won't.

**Comment by kolmodin** [comment]
I'm impressed how you found this usage of `tyConString` since it's not part of the actual library, or even referenced from the `.cabal` file :)

**Comment by treeowl** [comment]
binary is distributed with the GHC source tree, so I caught it in `grep -r`.

**Comment by treeowl** [comment]
And `tyConString` will be gone in GHC 8.2.

**Pull request merged**
