### PR TITLE
Add more ghcs to travis matrix

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Had to disable tests old older GHCs, because test dependencies cannot be build with them. Yet verifying that package builds is good too.

**Comment by phadej** [comment]
For some reason `ScopedTypeVariables` in other places didn't work. I have no idea what's wrong with GHC 6.12.3. 

Also benchmark setup is not superb. I'd recommend to make a separate package so the dep-cycle could be broken - would help development too. For example in aeson: https://github.com/bos/aeson/blob/master/benchmarks/aeson-benchmarks.cabal

**Comment by kolmodin** [comment]
The benchmark setup is indeed annoying. I'd wish cabal was better at handling this case, but I guess it's not a common enough scenario to be prioritized.

Who uses older GHCs? Even Debian stable ships with GHC 7.6.3.

**Comment by phadej** [comment]
> Who uses older GHCs? Even Debian stable ships with GHC 7.6.3.

Not me. But, if the older version aren't supported, one should say that in cabal file. i.e. restrict dependencies. OTOH if there isn't real reason not to support them, why not. As far as there is CI support (= travis).

**Comment by kolmodin** [comment]
I've restricted old versions of GHC in 4da61831229bf952225e50b8f8277ece89fd6ba0. Now only GHC >= 7.4 is supported.

**Pull request closed without merging**
