### PR TITLE
Instance for GHC.Fingerprint, which is part of base.

### PR DESCRIPTION
**Pull request by mboes**
Only enabled for GHC >= 7.4.

### CODE REVIEW

**Comment by kolmodin** [comment]
I'm a little bit reluctant to add an instance for `Fingerprint` since it seems that the format is not stable.

A comment in the code where GHC.Fingerprint is defined;
```haskell
-- Using 128-bit MD5 fingerprints for now.
```

It seems to me that the hashing function might change in the future, which would be very unfortunate for people who have serialized data using `Fingerprint`.

I think we should try to better understand `Fingerprint`, may the type change in the future? If so, user may run into unpleasant surprises here.

**Comment by mboes** [comment]
Yes but this instance serializes `Fingerprint`, irrespective of how it was produced (including which hash function was used). The instance is oblivious to future changes in the hash function, so long as the `Fingerprint` data type retains the same definition (note that the output of longer hash functions such as SHA-1 can safely be truncated to 128 bits).

If we are indeed worried, then I guess we could do something akin to the `Int` instance, which assumes that ints will never grow to be more than 64 bits in the future: serialize `Fingerprint` to 256 bits always, if we think that it's possible Fingerprint may grow to up to that size in the future. That'll be a pretty hefty overhead for applications like Cloud Haskell, however. Either that or include an extra byte at the beginning that specifies the size of the fingerprint? Or better yet, map a Fingerprint to an Integer and serialize that?

**Comment by kolmodin** [comment]
> Yes but this instance serializes Fingerprint, irrespective of how it was produced (including which hash function was used).

This is exactly my worry. The Fingerprint is not guaranteed to be stable, it could change with every GHC release.
It means that you could serialize with one version of GHC and then not be able to get the same result with another version of GHC.

OTOH, there is no documentation whatsever in `GHC.Fingerprint`, so developers using this better know what they're getting themselves into :)

We should add some tests in QC.hs for serialization/deserialization, then we're good to go.

**Comment by kolmodin** [comment]
Made the decoder strict, added QC roundtrip tests.

**Pull request merged**
