### PR TITLE
Use unsafe shifts from base rather than hand-rolling

### PR DESCRIPTION
**Pull request by Ericson2314**
This is a companion to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492.

I'm not sure why the second-to-top commit isn't already merged, as ghc HEAD relies on it.

CC @bgamari

### CODE REVIEW

**Comment by bgamari** [comment]
@Ericson2314, this was an oversight on my part; thanks for doing this!

Can we get this merged, @kolmodin?

**Comment by Ericson2314** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492 is now just blocked on upstream libraries approving these PRs. (The current rebuild as I write this is just from me changing the a changeg log message.)

**Comment by Ericson2314** [comment]
According to https://github.com/haskell/bytestring/pull/326 these manual unboxed shifts for static shit amounts are no longer needed at all.

**Comment by Ericson2314** [comment]
And even better, `base` within the version range supported, always provides the very unsafe shifts we want!

**Comment by Ericson2314** [comment]
@kolmodin Can we merge this? It no longer makes any assumptions about the state of 9.2. As you can see in the description of https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492, some of the others have gotten merged.

**Comment by bgamari** [comment]
Pinging @kolmodin?

**Comment by bgamari** [comment]
Looks good. The `base` bound is already `>= 4.5.0.0` so it looks like this is good to go.

**Pull request merged**
