### PR TITLE
Handle {Int,Word}32Rep

### PR DESCRIPTION
**Pull request by Ericson2314**
This is for an *unmerged* GHC PR (https://gitlab.haskell.org/ghc/ghc/merge_requests/1148). But I'm not sure how to ensure the commit is availible on my branch from the current submodule without opening a PR here. Until the GHC one merged, sorry for the noise.

### CODE REVIEW

**Comment by Ericson2314** [comment]
https://gitlab.haskell.org/ghc/ghc/merge_requests/1148 Is now approved, but this needs to be merged before that can be merged.

**Comment by bgamari** [comment]
Pinging @kolmodin,

**Comment by bgamari** [comment]
@kolmodin, ping.

**Comment by kolmodin** [comment]
Sorry for the delay. I'm still OOO until next weekend.
The travis build has broken (again) so this change cannot be properly tested. But it looks OK to me. Merging.

**Comment by Ericson2314** [comment]
Thank you!

**Pull request merged**
