### PR TITLE
Don't use * as Type in the presence of TypeOperators

### PR DESCRIPTION
**Pull request by int-index**

### CODE REVIEW

**Comment by int-index** [comment]
I need this for https://phabricator.haskell.org/D4748

**Comment by kolmodin** [comment]
From Travis,

```

src/Data/Binary/Generic.hs:30:8:
    Could not find module `Data.Kind'
    Use -v to see a list of the files searched for.

```

does this change work with older GHCs?

**Comment by int-index** [comment]
> does this change work with older GHCs?

Not yet. I'll add CPP conditionals to fix it.

**Comment by int-index** [comment]
This now builds on all GHC versions from 7.4.2 to 8.4.3

**Pull request merged**
